title: YA-Hwang 기술 블로그
description: 데이터 분석을 위한 포트폴리오
permalink: 'posts/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yahwang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul # 지역 시간 설정

# Author Settings
author: YA-Hwang # add your name
author-img: yahwang_logo.png # add your photo
about-author: Yes to Ambition! # add description
facebook: # add your Facebook handle
github: yahwang # add your Github handle
linkedin: # add your Linkedin handle
dropbox: https://www.dropbox.com/sh/h8vq5tnmur3922n/AAAK4lgPY7rgkot60WwSksfWa?dl=0
email: ts.yahwang@gmail.com # add your Email address
evernoter: https://www.evernote.com/pub/hts911kr/r
evernotepy: https://www.evernote.com/pub/hts911kr/python
# Disqus
discus-identifier: yahwang # add your discus identifier

sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate

# pagination settings
paginate: 10
paginate_path: "/posts/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Search settings
tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []
