title: YaHwang 기술 블로그
description: 데이터를 공부합니다. 빅데이터, r, python, tableau 등의 기술을 배우고 4차 산업혁명 시대를 준비한다.
permalink: ':year/:month/:day/:title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul # 지역 시간 설정

# Author Settings
author: 황 태 식 # add your name
author-img: yahwang_logo.png # add your photo
about-author: Be Ambitious! # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: yahwang # add your Github handle
linkedin: # add your Linkedin handle
dropbox: https://www.dropbox.com/sh/h8vq5tnmur3922n/AAAK4lgPY7rgkot60WwSksfWa?dl=0
email: hts911kr@gmail.com # add your Email address

# Disqus
discus-identifier: YaHwang # add your discus identifier

sass:
  sass_dir: _sass
  style: compressed

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# pagination
paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
